name = "Hypno MC"
author = "Adri"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b8f3fa339d20a386d84906f7c9d370a9ff4b3c62e34960ea46f32f605a7921f2"

[versions]
fabric = "0.19.3"
minecraft = "26.1.2"
